apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - ecompoc-node-affinity.yaml
  - ui-node-affinity.yaml
  - ecompoc-resources.yaml

