apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      nodeSelector:
        kubernetes.azure.com/agentpool: spotnode
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      containers:
        - name: ui
          image: rgpocacr9021.azurecr.io/ui:latest
          ports:
            - containerPort: 80
          env:
            - name: DEPLOYMENT_COLOR
              value: "blue"
            - name: NAMESPACE
              value: "dev"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

