apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ui-nginx-configmap.yaml

images:
  - name: rgpocacr9021.azurecr.io/monolith
    newName: monolith
    newTag: local
  - name: rgpocacr9021.azurecr.io/ui
    newName: ui
    newTag: local

patchesStrategicMerge:
  - monolith-deployment-patch.yaml
  - ui-deployment-patch.yaml

