apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ui-nginx-configmap.yaml

images:
  - name: rgpocacr9021.azurecr.io/ecompoc
    newName: ecompoc
    newTag: local
  - name: rgpocacr9021.azurecr.io/ui
    newName: ui
    newTag: local

patchesStrategicMerge:
  - ecompoc-deployment-patch.yaml
  - ui-deployment-patch.yaml

