apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  namespace: dev
spec:
  template:
    spec:
      tolerations: []
      containers:
        - name: monolith
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=30"

