apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: dev
spec:
  template:
    spec:
      # Remove cloud-specific tolerations
      tolerations: []
      containers:
        - name: user
          imagePullPolicy: Never
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
            # Remove SQL_SERVER_PASSWORD since we're using H2
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=30"

